#!/usr/bin/env bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
ROOT="$(cd $HERE/.. && pwd)"
CLASSICO=$ROOT
. $CLASSICO/shibumi/defs

if [[ $BASH_VERSINFO == 3 ]]; then
	perror "Bash version is too old - please install Bash 5 and retry."
	exit 1
fi

os="$(platform_os)"

export HOMEBREW_NO_AUTO_UPDATE=1

$CLASSICO/shibumi/setup

if [[ $os == windows ]]; then
	posh <<-'END'
		. $CLASSICO/bin/getget.ps1
		END
fi
$CLASSICO/bin/getget
$CLASSICO/bin/getbashdb
$CLASSICO/bin/getgnu

profile_d="$(get_profile_d)"

cat <<-END > $profile_d/dotlocal.sh
	prepend_to_path $HOME/.local/bin
	END

if [[ $os == windows ]]; then
	cat <<-'END' > $profile_d/windows.sh
		append_to_path /c/ProgramData/chocolatey/bin:$(cygpath $USERPROFILE)/scoop/shims
		append_to_path $(cygpath $USERPROFILE)/AppData/Local/Microsoft/WindowsApps
		END
fi

rearm

runn $CLASSICO/bin/getpy
rearm

if [[ $os == windows ]]; then
	runn $CLASSICO/bin/getnode --modern --ts
else
	runn $CLASSICO/bin/getnode --modern --bun
fi
rearm

runn $HERE/system-setup

if [[ $VERBOSE == 1 ]]; then
	python --version
	uv pip list
	node --version
	npm --version
	[[ $os != windows ]] && bun --version
fi
