#!/bin/bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
ROOT=$(cd $HERE/.. && pwd)
CLASSICO=$ROOT
. $CLASSICO/shibumi/defs

export HOMEBREW_NO_AUTO_UPDATE=1

$CLASSICO/bin/getget

profile_d="$(get_profile_d)"

tmp_profiled=$(mktemp -d)
cat <<-'END' > $tmp_profiled/dotlocal.sh
	if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
	    export PATH="$HOME/.local/bin${PATH:+":$PATH"}"
	fi
	END
add_to_profile_d $tmp_profiled/dotlocal.sh
rm -rf $tmp_profiled

$CLASSICO/bin/getpy
. "$(profile_d)/python.sh"

if [[ $VERBOSE == 1 ]]; then
	python --version
	python -m pip list
fi

$CLASSICO/bin/getnode --bun
$HERE/system-setup
