#!/usr/bin/env bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
ROOT="$(cd $HERE/.. && pwd)"
CLASSICO=$ROOT
. $CLASSICO/shibumi/defs

if [[ $BASH_VERSINFO == 3 ]]; then
	perror "Bash version is too old - please install Bash 5 and retry."
	exit 1
fi

export HOMEBREW_NO_AUTO_UPDATE=1

$CLASSICO/shibumi/setup

$CLASSICO/bin/getget
$CLASSICO/bin/getgnu

profile_d="$(get_profile_d)"

tmp_profiled=$(mktemp -d)
cat <<-'END' > $tmp_profiled/dotlocal.sh
	if [[ ":$PATH:" != *":$HOME/.local/bin:"* ]]; then
	    export PATH="$HOME/.local/bin${PATH:+":$PATH"}"
	fi
	END
add_to_profile_d $tmp_profiled/dotlocal.sh
rm -rf $tmp_profiled
rearm

runn $CLASSICO/bin/getpy
rearm

runn $CLASSICO/bin/getnode --modern --bun
rearm

runn $HERE/system-setup

if [[ $VERBOSE == 1 ]]; then
	python --version
	uv pip list
	node --version
	npm --version
	bun --version
fi
