#!/usr/bin/env python3

import sys
import os
import argparse

HERE = os.path.dirname(__file__)
ROOT = os.path.abspath(os.path.join(HERE, ".."))
CLASSICO = ROOT
sys.path.insert(0, ROOT)
import paella

#----------------------------------------------------------------------------------------------

class SystemSetup(paella.Setup):
    def __init__(self, args):
        paella.Setup.__init__(self, args.nop)

    def common_first(self):
        self.install_downloaders()
        self.setup_dotlocal()

    def linux_first(self):
        pass

    def debian_compat(self):
        pass

    def redhat_compat(self):
        pass

    def archlinux(self):
        pass

    def fedora(self):
        pass

    def linux_last(self):
        pass

    def macos(self):
        self.install_gnu_utils()

    def common_last(self):
        pass

#----------------------------------------------------------------------------------------------

parser = argparse.ArgumentParser(description='Set up system for build.')
parser.add_argument('-n', '--nop', action="store_true", help='no operation')
# parser.add_argument('--bool', action="store_true", help="flag")
# parser.add_argument('--int', type=int, default=1, help='number')
# parser.add_argument('--str', type=str, default='str', help='string')
# parser.add_argument("--mode", choices=["fast", "slow", "medium"], default="medium")
# parser.add_argument("--summary", choices=["short", "long"], nargs="?", const="short")  # None if not present
args = parser.parse_args()

SystemSetup(args).setup()
