[package]
name = "classico-wd40"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
crate-type = ["rlib"]
name = "classico_wd40"
path = "src/lib.rs"

[[bin]]
name = "wd40-test"
path = "src/bin.rs"

[dependencies]
bindgen = "0.65"

[build-dependencies]
bindgen = "0.65"
