[package]
name = "classico-wd40"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
crate-type = ["rlib"]
name = "classico"
path = "src/lib.rs"

#[[bin]]
#name = "bb"
#path = "src/bin/bb.rs"

[dependencies]
bindgen = "0.65"

[build-dependencies]
bindgen = "0.65"
