#!/usr/bin/env bash

PROGNAME="${BASH_SOURCE[0]}"
HERE="$(cd "$(dirname "$PROGNAME")" &>/dev/null && pwd)"
CLASSICO="$(cd $HERE/../.. && pwd)"
. $CLASSICO/shibumi/defs

if [[ $UNINSTALL == 1 ]]; then
	net stop msys2_sshd || :
	cygrunsrv -R msys2_sshd 2>/dev/null || :
	net user sshd //delete || :
	exit 0
fi

runn pacman --noconfirm --needed -S openssh cygrunsrv mingw-w64-x86_64-editrights
$HERE/msys2-sshd-setup.sh
ssh_dir="$(win_homedir)/.ssh"
mkdir -p "$ssh_dir"
ln -sf "$ssh_dir" ~/.ssh
if [[ -n $PUBKEY ]]; then
	echo "$PUBKEY" >> ~/.ssh/authorized_keys
fi

posh <<-'END'
	$POSH = [System.IO.Path]::Combine($CLASSICO, "posh")
	. "$POSH\defs.ps1"
    New-FirewallRule -Name "OpenSSH" -Port 22 -DisplayName "OpenSSH (Port 22)"
    END
