#!/usr/bin/env python

import sys
import os
import argparse

HERE = os.path.dirname(__file__)
CLASSICO = os.path.abspath(os.path.join(HERE, "../.."))
sys.path.insert(0, CLASSICO)
import paella

#----------------------------------------------------------------------------------------------

class SystemSetup(paella.Setup):
    def __init__(self, args):
        paella.Setup.__init__(self, args.nop)

    def common_first(self):
        pass

    def linux_first(self):
        pass

    def debian_compat(self):
        pass

    def redhat_compat(self):
        pass

    def archlinux(self):
        pass

    def fedora(self):
        pass

    def linux_last(self):
        pass

    def macos(self):
        pass

    def common_last(self):
        pass

#----------------------------------------------------------------------------------------------

parser = argparse.ArgumentParser(description='Set up system for build.')
parser.add_argument('-n', '--nop', action="store_true", help='no operation')
# parser.add_argument('--bool', action="store_true", help="flag")
# parser.add_argument('--int', type=int, default=1, help='number')
# parser.add_argument('--str', type=str, default='str', help='string')
# parser.add_argument("--mode", choices=["fast", "slow", "medium"], default="medium")
# parser.add_argument("--summary", choices=["short", "long"], nargs="?", const="short")  # None if not present
# parser.add_argument('-x', dest="long_x", type=str, metavar="DIR", help='do something in DIR')
# parser.add_argument('name', nargs='?', type=str, help='name')
# parser.add_argument("args", nargs=argparse.REMAINDER, help='arguments')

args = parser.parse_args()

SystemSetup(args).setup()
